services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: mhcloud-code
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Seoul
      - PASSWORD=jj331183450.
      - SUDO_PASSWORD=jj331183450.
      - DEFAULT_WORKSPACE=/config/workspace
    volumes:
      - ./config:/config
    ports:
      - "8443:8443"
    restart: unless-stopped
